import type { HuntLocation } from './types';

export const LOCATIONS: HuntLocation[] = [
  {
    id: 'st-georges-hall',
    name: "St George's Hall",
    themes: ['urban', 'hidden'],
    lat: 53.4083,
    lng: -2.9795,
    distanceToFinish: 1100,
    feature: 'A vast neo-classical concert hall with a tunnel-like entrance hall and mosaic floors.',
    clues: {
      easy: 'Find the giant stone concert hall with tall columns, opposite the station with the big screen.',
      medium:
        'A Roman-temple facade looms over the city\u2019s main rail station. Stand under its colonnade and listen for the echo under the vaulted ceiling.',
      hard: 'Cross the road from Lime Street and pass through the colonnade of this neo-classical giant. Find the entrance to the great hall and note the mosaic floor pattern inside the vestibule.',
    },
    reveal: 'St George\u2019s Hall \u2014 one of the finest neo-classical buildings in Europe.',
  },
  {
    id: 'central-library',
    name: 'Liverpool Central Library',
    themes: ['urban', 'hidden'],
    lat: 53.4089,
    lng: -2.9802,
    distanceToFinish: 1050,
    feature: 'A circular glass-roofed reading room inside a modern library.',
    clues: {
      easy: 'Walk into the big modern library near William Brown Street and look up at the round glass roof.',
      medium:
        'Behind the historic facade there\u2019s a brand-new atrium. Climb the spiral and stand under the domed glass roof that rings with quiet footsteps.',
      hard: 'Enter the library on William Brown Street and ascend to the rotunda. Count the levels of bookshelves wrapping the circular atrium beneath the domed roof.',
    },
    reveal: 'The Hornby Library and rotunda \u2014 a hidden modern heart inside a historic shell.',
  },
  {
    id: 'williamson-square',
    name: 'Williamson Square',
    themes: ['urban', 'music'],
    lat: 53.4058,
    lng: -2.9790,
    distanceToFinish: 850,
    feature: 'A pedestrian square with a fountain and the Liverpool Playhouse theatre.',
    clues: {
      easy: 'Find the pedestrian square with a fountain and a theatre called the Playhouse.',
      medium:
        'A pedestrian square hides between the shopping streets. Find the fountain, then look for the theatre that has been staging plays here since 1911.',
      hard: 'Reach the square off Williamson Street. Identify the bronze plaque marking the oldest repertory theatre in England, then note the inscription on the fountain.',
    },
    reveal: 'The Playhouse Theatre \u2014 one of England\u2019s oldest repertory theatres.',
  },
  {
    id: 'bold-street',
    name: 'Bold Street',
    themes: ['urban', 'hidden'],
    lat: 53.4042,
    lng: -2.9775,
    distanceToFinish: 750,
    feature: 'A sloped street of independent caf\u00e9s, record shops and world food.',
    clues: {
      easy: 'Walk down the famous sloped street full of independent caf\u00e9s and record shops.',
      medium:
        'This street runs downhill from the cathedrals to the shopping core. Find a record shop or an independent caf\u00e9 and read the chalkboard outside.',
      hard: 'Walk the length of Bold Street from its top near Berry Street. Count the independent coffee roasters you pass and note the name of the oldest record shop on the street.',
    },
    reveal: 'Bold Street \u2014 Liverpool\u2019s independent heart.',
  },
  {
    id: 'cavern-quarter',
    name: 'Cavern Quarter & Mathew Street',
    themes: ['music', 'urban'],
    lat: 53.4075,
    lng: -2.9920,
    distanceToFinish: 700,
    feature: 'The alley where the Cavern Club sits, covered in Beatles names.',
    clues: {
      easy: 'Find the narrow alley covered in Beatles names and a famous underground club.',
      medium:
        'A short alley is paved with the names of every artist who played the city\u2019s most famous cellar. Find the club entrance below street level.',
      hard: 'Enter Mathew Street and locate the Cavern Club. Read the wall of inductee names, then find the bronze statue standing at the corner of the street.',
    },
    reveal: 'The Cavern Club \u2014 where the Beatles played nearly 300 times.',
  },
  {
    id: 'castle-street',
    name: 'Castle Street & Town Hall',
    themes: ['urban', 'hidden'],
    lat: 53.4072,
    lng: -2.9945,
    distanceToFinish: 600,
    feature: 'A civic square with the Liverpool Town Hall and a column monument.',
    clues: {
      easy: 'Find the grand civic square with the Town Hall and a tall column statue.',
      medium:
        'A formal square holds the city\u2019s 18th-century Town Hall. Stand by the column and look up at the statue on top.',
      hard: 'Reach Castle Street and identify the figure atop the Nelson Monument. Count the bronze relief panels around its base.',
    },
    reveal: 'Liverpool Town Hall and the Nelson Monument.',
  },
  {
    id: 'royle-bank',
    name: 'The Bank Building (Castle Street)',
    themes: ['urban', 'hidden'],
    lat: 53.4070,
    lng: -2.9950,
    distanceToFinish: 580,
    feature: 'A former bank turned grand caf\u00e9-bar with vaulted ceilings.',
    clues: {
      easy: 'Find the grand old bank building turned into a caf\u00e9-bar on Castle Street.',
      medium:
        'A former bank on Castle Street is now a caf\u00e9. Step inside and look up at the vaulted ceiling and the brass teller counters still in place.',
      hard: 'Enter the Bank Building on Castle Street. Find the original safety deposit vault door and note the manufacturer\u2019s name cast into the steel.',
    },
    reveal: 'The Bank Building \u2014 a cathedral of coffee inside a former bank.',
  },
  {
    id: 'museum-liverpool',
    name: 'Museum of Liverpool Pier Head',
    themes: ['waterfront', 'urban'],
    lat: 53.4015,
    lng: -2.9955,
    distanceToFinish: 350,
    feature: 'A striking modern white building on the Pier Head with views over the Mersey.',
    clues: {
      easy: 'Find the big white modern museum right on the waterfront at the Pier Head.',
      medium:
        'A white wedge-shaped museum sits between the Three Graces and the river. Walk up its ramp and find the window looking out to the ferry terminal.',
      hard: 'Enter the Museum of Liverpool and locate the Liverpolitan gallery. Find the original Overhead Railway carriage on display and read its destination board.',
    },
    reveal: 'Museum of Liverpool \u2014 the story of the city, told on the waterfront.',
  },
  {
    id: 'three-graces',
    name: 'The Three Graces (Pier Head)',
    themes: ['waterfront', 'urban'],
    lat: 53.4043,
    lng: -2.9975,
    distanceToFinish: 300,
    feature: 'Three iconic waterfront buildings crowned by the Liver Birds.',
    clues: {
      easy: 'Stand in front of the three famous waterfront buildings and spot the Liver Birds on top.',
      medium:
        'Three grand buildings line the Pier Head. Find the one with the clock and the two birds on its roof, then look for the statue of a man with a folded map nearby.',
      hard: 'At the Pier Head, identify the Royal Liver Building, the Cunard Building and the Port of Liverpool Building. Find the statue of John Lennon at the waterfront and note the lyric inscribed beneath him.',
    },
    reveal: 'The Three Graces \u2014 Liverpool\u2019s postcard skyline, crowned by the Liver Birds.',
  },
  {
    id: 'mersey-ferry',
    name: 'Mersey Ferry Terminal',
    themes: ['waterfront', 'music'],
    lat: 53.4010,
    lng: -2.9980,
    distanceToFinish: 280,
    feature: 'The ferry terminal where the Mersey Ferry departs.',
    clues: {
      easy: 'Find the ferry terminal where the famous Mersey Ferry departs.',
      medium:
        'A green-domed terminal building is the departure point for the ferry across the Mersey. Find the song lyric quoted on the terminal signage.',
      hard: 'Reach the Mersey Ferry terminal at the Pier Head. Identify the artist who recorded Ferry Cross the Mersey and find the year the ferry service first began, shown on the heritage board.',
    },
    reveal: 'The Mersey Ferry \u2014 \u201CFerry Cross the Mersey\u201D since 1965.',
  },
  {
    id: 'albert-dock',
    name: 'Albert Dock',
    themes: ['waterfront', 'music', 'hidden'],
    lat: 53.4005,
    lng: -2.9995,
    distanceToFinish: 0,
    feature: 'A vast complex of red-brick warehouses around a working dock, home to Tate Liverpool.',
    clues: {
      easy: 'You\u2019ve reached the finish: the famous red-brick dock with the big modern art gallery.',
      medium:
        'The final stop is the largest collection of Grade I listed warehouses in the UK. Find the entrance to the modern art gallery inside the dock complex.',
      hard: 'Enter Albert Dock and locate Tate Liverpool. Find the heritage plaque describing the dock\u2019s opening year and the name of the architect who designed it.',
    },
    reveal: 'Albert Dock \u2014 opened in 1846, the heart of Liverpool\u2019s waterfront rebirth.',
  },
  {
    id: 'tate-liverpool',
    name: 'Tate Liverpool',
    themes: ['waterfront', 'hidden'],
    lat: 53.4030,
    lng: -3.0010,
    distanceToFinish: 50,
    feature: 'A modern art gallery inside a converted dock warehouse.',
    clues: {
      easy: 'Find the modern art gallery inside the Albert Dock warehouses.',
      medium:
        'Inside the Albert Dock complex, a modern art gallery occupies a former warehouse. Find the free permanent collection entrance.',
      hard: 'Locate Tate Liverpool within Albert Dock. Identify the artist whose work is displayed on the fourth-floor landing of the permanent collection and note the title.',
    },
    reveal: 'Tate Liverpool \u2014 modern art in a historic dock warehouse.',
  },
  {
    id: 'maritime-museum',
    name: 'Maritime Museum',
    themes: ['waterfront', 'hidden'],
    lat: 53.4035,
    lng: -3.0005,
    distanceToFinish: 30,
    feature: 'A museum of seafaring and emigration inside the Albert Dock.',
    clues: {
      easy: 'Find the museum about ships and the sea, inside the Albert Dock.',
      medium:
        'A museum in the Albert Dock tells the story of emigration and the Titanic. Find the gallery about the ship on the second floor.',
      hard: 'Enter the Merseyside Maritime Museum. Locate the Titanic, Lusitania and Empress of Ireland gallery and note the name of the violin recovered from the wreck.',
    },
    reveal: 'Merseyside Maritime Museum \u2014 stories of the sea and the city.',
  },
  {
    id: 'chinese-arch',
    name: 'Chinese Arch & Chinatown',
    themes: ['urban', 'hidden', 'music'],
    lat: 53.4060,
    lng: -2.9810,
    distanceToFinish: 900,
    feature: 'Europe\u2019s largest multi-storey Chinese arch at the entrance to Chinatown.',
    clues: {
      easy: 'Find the giant colourful Chinese arch at the entrance to Chinatown.',
      medium:
        'Europe\u2019s largest multi-storey Chinese arch stands at the top of a short street of restaurants. Walk under it and read the plaque.',
      hard: 'Reach the ceremonial arch on Nelson Street. Count the number of storeys and identify the two Chinese cities named on the twin plaques either side of the arch.',
    },
    reveal: 'The Chinatown Arch \u2014 13.5 metres high, a gift from Shanghai.',
  },
  {
    id: 'bombed-church',
    name: 'St Luke\u2019s Bombed Church',
    themes: ['hidden', 'music'],
    lat: 53.4040,
    lng: -2.9750,
    distanceToFinish: 820,
    feature: 'A roofless bombed-out church used as a venue and garden.',
    clues: {
      easy: 'Find the old church with no roof, now a garden and event space.',
      medium:
        'A church bombed in the Blitz was left roofless and is now a venue. Find the garden entrance and the stage inside the ruins.',
      hard: 'Reach St Luke\u2019s on Leece Street. Identify the year it was bombed and find the memorial plaque near the main entrance gates.',
    },
    reveal: 'St Luke\u2019s \u2014 the \u201Cbombed-out church\u201D, a living ruin and venue.',
  },
  {
    id: 'liverpool-cathedral',
    name: 'Liverpool Anglican Cathedral',
    themes: ['urban', 'hidden'],
    lat: 53.4010,
    lng: -2.9740,
    distanceToFinish: 1300,
    feature: 'The largest cathedral in Britain, Gothic and vast, with a tower viewing gallery.',
    clues: {
      easy: 'Find the biggest cathedral in Britain, a giant Gothic building on St James\u2019 Mount.',
      medium:
        'A vast Gothic cathedral dominates the skyline. Enter through the west doors and find the modern stained-glass window at the far end.',
      hard: 'Enter Liverpool Cathedral and find the Tracy Emin work near the entrance. Identify the longest nave in the world and note the height of the tower viewing gallery in metres.',
    },
    reveal: 'Liverpool Anglican Cathedral \u2014 the largest in Britain.',
  },
  {
    id: 'philharmonic-hall',
    name: 'Liverpool Philharmonic Hall',
    themes: ['music', 'urban'],
    lat: 53.3995,
    lng: -2.9705,
    distanceToFinish: 950,
    feature: 'A 1930s art-deco concert hall and home of the Royal Liverpool Philharmonic.',
    clues: {
      easy: 'Find the art-deco concert hall on Hope Street, home of the city\u2019s philharmonic orchestra.',
      medium:
        'A 1930s art-deco hall sits on Hope Street. Find the engraved orchestra name above the entrance and the brass plaque of past conductors.',
      hard: 'Reach the Philharmonic Hall on Hope Street. Identify the founding year of the Royal Liverpool Philharmonic and the name of the hall\u2019s principal conductor during WWII, shown on the heritage trail board.',
    },
    reveal: 'The Philharmonic Hall \u2014 home of the Royal Liverpool Philharmonic.',
  },
  {
    id: 'philharmonic-pub',
    name: 'The Philharmonic Dining Rooms',
    themes: ['music', 'hidden'],
    lat: 53.3998,
    lng: -2.9708,
    distanceToFinish: 930,
    feature: 'A spectacular Grade I listed pub with ornate gents\u2019 toilets.',
    clues: {
      easy: 'Find the grand old pub across from the Philharmonic Hall with famous fancy toilets.',
      medium:
        'A Grade I listed pub sits opposite the concert hall. Find the entrance to its ornate gentlemen\u2019s lavatories, listed as a heritage attraction.',
      hard: 'Enter the Philharmonic Dining Rooms on Hope Street. Identify the architect of the interior and note the material of the gents\u2019 urinal stalls, which are Grade I listed.',
    },
    reveal: 'The Philharmonic Dining Rooms \u2014 a pub so grand its toilets are listed.',
  },
  {
    id: 'walker-art-gallery',
    name: 'Walker Art Gallery',
    themes: ['urban', 'hidden'],
    lat: 53.4095,
    lng: -2.9798,
    distanceToFinish: 1000,
    feature: 'A major art gallery with works from medieval to contemporary.',
    clues: {
      easy: 'Find the big art gallery near St George\u2019s Hall, with stone lions at the door.',
      medium:
        'A grand gallery stands near St George\u2019s Hall. Find the entrance with the stone lions and look for the Hockney or Freud in the modern rooms.',
      hard: 'Enter the Walker Art Gallery and locate the room of Pre-Raphaelite works. Identify the artist of \u201CThe Scapegoat\u201D and note the year it was painted.',
    },
    reveal: 'The Walker Art Gallery \u2014 the \u201CNational Gallery of the North\u201D.',
  },
  {
    id: 'lime-street-station',
    name: 'Lime Street Station',
    themes: ['urban'],
    lat: 53.4073,
    lng: -2.9785,
    distanceToFinish: 1080,
    feature: 'The grand mainline rail station with a concourse and the old station hotel.',
    clues: {
      easy: 'Find the city\u2019s biggest train station, the one with the giant screen on the wall.',
      medium:
        'Walk into the main concourse of the city\u2019s principal rail terminus. Find the former North Western Hotel building visible across the road.',
      hard: 'Enter Lime Street Station. Identify the year the original station opened and find the statue of Ken Dodd in the concourse, noting the feather duster in his hand.',
    },
    reveal: 'Lime Street \u2014 the world\u2019s first intercity passenger rail terminus.',
  },
  {
    id: 'st-johns-gardens',
    name: "St John's Gardens",
    themes: ['urban', 'hidden'],
    lat: 53.4090,
    lng: -2.9770,
    distanceToFinish: 1020,
    feature: 'A formal garden behind St George\u2019s Hall with statues of civic figures.',
    clues: {
      easy: 'Find the formal garden behind the big concert hall, with statues of people on plinths.',
      medium:
        'Behind St George\u2019s Hall lies a terraced garden. Find the row of bronze statues and identify the figure holding a scroll.',
      hard: 'Enter St John\u2019s Gardens from William Brown Street. Count the memorial statues and identify the only woman commemorated among them.',
    },
    reveal: 'St John\u2019s Gardens \u2014 a Victorian pleasure garden behind the hall.',
  },
  {
    id: 'empire-theatre',
    name: 'Liverpool Empire Theatre',
    themes: ['music', 'urban'],
    lat: 53.4068,
    lng: -2.9780,
    distanceToFinish: 970,
    feature: 'The largest two-tier theatre in the UK, hosting musicals and concerts.',
    clues: {
      easy: 'Find the big theatre on Lime Street, next to the station, with a bright LED sign.',
      medium:
        'A large theatre sits on Lime Street opposite the station. Find the entrance canopy and the plaque listing past performers.',
      hard: 'Reach the Liverpool Empire on Lime Street. Identify the year it opened as a theatre and find the name of the Beatles\u2019 last Liverpool performance venue shown on the heritage board.',
    },
    reveal: 'The Empire \u2014 the largest two-tier theatre in Britain.',
  },
  {
    id: 'everyman-theatre',
    name: 'Everyman Theatre',
    themes: ['music', 'urban'],
    lat: 53.4048,
    lng: -2.9765,
    distanceToFinish: 780,
    feature: 'A rebuilt theatre on Hope Street with a distinctive red-letter facade.',
    clues: {
      easy: 'Find the theatre on Hope Street with the sign made of giant red letters.',
      medium:
        'A theatre on Hope Street has a facade of oversized red movable type. Find the entrance and the engraved wall plaque.',
      hard: 'Reach the Everyman Theatre on Hope Street. Identify the architect of the 2014 rebuild and find the name of the most famous playwright who began their career here.',
    },
    reveal: 'The Everyman \u2014 a theatre that has nurtured generations of talent.',
  },
  {
    id: 'metropolitan-cathedral',
    name: 'Liverpool Metropolitan Cathedral',
    themes: ['urban', 'hidden'],
    lat: 53.4035,
    lng: -2.9730,
    distanceToFinish: 880,
    feature: 'A modern Catholic cathedral shaped like a crown, floodlit at night.',
    clues: {
      easy: 'Find the modern round cathedral that looks like a crown, at the top of Hope Street.',
      medium:
        'A concrete Catholic cathedral sits at the top of Hope Street. Walk inside and find the coloured glass panels around the central altar.',
      hard: 'Enter the Metropolitan Cathedral. Identify the architect and the year the cathedral was consecrated, shown on the foundation stone near the entrance.',
    },
    reveal: 'Paddy\u2019s Wigwam \u2014 the Metropolitan Cathedral of Christ the King.',
  },
  {
    id: 'liverpool-one',
    name: 'Liverpool ONE',
    themes: ['urban'],
    lat: 53.4045,
    lng: -2.9860,
    distanceToFinish: 500,
    feature: 'A large open-air shopping centre built around Chavasse Park.',
    clues: {
      easy: 'Find the big modern shopping centre with a park on top, near the docks.',
      medium:
        'A vast open-air shopping district has a park on its roof. Find the staircase to Chavasse Park and the view from the top.',
      hard: 'Navigate to Liverpool ONE. Find the park on the upper level, identify the church spire visible from the top of the park, and note the name of the dock that once occupied this site.',
    },
    reveal: 'Liverpool ONE \u2014 the city\u2019s modern shopping heart.',
  },
  {
    id: 'concert-square',
    name: 'Concert Square',
    themes: ['urban', 'music'],
    lat: 53.4055,
    lng: -2.9870,
    distanceToFinish: 550,
    feature: 'A lively square of bars and clubs off Bold Street.',
    clues: {
      easy: 'Find the lively square full of bars and clubs, just off Bold Street.',
      medium:
        'A pedestrian square off Bold Street is ringed with bars. Find the one with the outdoor terrace and the big screen on the wall.',
      hard: 'Reach Concert Square. Identify the oldest bar on the square and note the year it opened, shown on the plaque near the entrance.',
    },
    reveal: 'Concert Square \u2014 the heart of Liverpool\u2019s nightlife.',
  },
  {
    id: 'baltic-triangle',
    name: 'Baltic Triangle',
    themes: ['urban', 'hidden'],
    lat: 53.3985,
    lng: -2.9745,
    distanceToFinish: 700,
    feature: 'A creative quarter of warehouses, street art and independent bars.',
    clues: {
      easy: 'Find the area of old warehouses covered in street art, south of the cathedral.',
      medium:
        'A district of converted warehouses lies south of the Anglican Cathedral. Find a piece of street art on a gable end and read the artist\u2019s tag.',
      hard: 'Enter the Baltic Triangle from Greenland Street. Identify the name of the brewery located here and find the year the area was designated a creative quarter.',
    },
    reveal: 'The Baltic Triangle \u2014 Liverpool\u2019s creative quarter.',
  },
  {
    id: 'mann-island',
    name: 'Mann Island',
    themes: ['waterfront', 'urban'],
    lat: 53.4025,
    lng: -2.9965,
    distanceToFinish: 200,
    feature: 'A modern black-glass building between the Pier Head and Albert Dock.',
    clues: {
      easy: 'Find the striking black-glass building between the Pier Head and the docks.',
      medium:
        'Three black wedge-shaped buildings sit between the Three Graces and Albert Dock. Walk between them and find the open public space on the water side.',
      hard: 'Reach Mann Island. Identify the architect of the buildings and find the memorial to the engineers of the Titanic, noting the names listed.',
    },
    reveal: 'Mann Island \u2014 a modern counterpoint to the historic waterfront.',
  },
  {
    id: 'beatles-statue',
    name: 'The Beatles Statue',
    themes: ['music', 'waterfront'],
    lat: 53.4038,
    lng: -2.9968,
    distanceToFinish: 250,
    feature: 'A bronze statue of the Beatles on the Pier Head promenade.',
    clues: {
      easy: 'Find the bronze statue of four musicians standing together on the waterfront.',
      medium:
        'A larger-than-life bronze statue of the Beatles stands on the Pier Head. Find it and note which band member is at the front.',
      hard: 'Reach the Beatles Statue at the Pier Head. Identify the sculptor and the year it was unveiled, shown on the plaque at the base.',
    },
    reveal: 'The Beatles Statue \u2014 the most photographed statue in Liverpool.',
  },
  {
    id: 'eleanor-rigby',
    name: 'Eleanor Rigby Statue',
    themes: ['music', 'hidden'],
    lat: 53.4078,
    lng: -2.9885,
    distanceToFinish: 650,
    feature: 'A bronze statue of a woman on a bench, dedicated to Eleanor Rigby.',
    clues: {
      easy: 'Find the bronze statue of a woman sitting on a bench, with a bird on her shoulder.',
      medium:
        'A life-size bronze of a woman sits on a bench on Stanley Street. Find her and read the plaque at her feet.',
      hard: 'Reach the Eleanor Rigby statue. Identify the sculptor and the biblical figure referenced on the plaque, then note the name of the real Eleanor Rigby\u2019s grave site.',
    },
    reveal: 'Eleanor Rigby \u2014 a statue dedicated to all the lonely people.',
  },
  {
    id: 'hardman-street',
    name: 'Hardman Street',
    themes: ['urban', 'hidden'],
    lat: 53.4038,
    lng: -2.9748,
    distanceToFinish: 860,
    feature: 'A Georgian street of grand houses, home to the Hardman\u2019s House museum.',
    clues: {
      easy: 'Find the street of grand Georgian houses near the Metropolitan Cathedral, with a blue plaque on one of them.',
      medium:
        'A street of Georgian terraces runs near the Catholic Cathedral. Find the house with a blue plaque and a camera shop sign above the door.',
      hard: 'Reach 59 Rodney Street (the Hardman\u2019s House). Identify the photographer who lived here and find the year the house was opened to the public by the National Trust.',
    },
    reveal: 'Rodney Street and the Hardman\u2019s House \u2014 a Georgian time capsule.',
  },
  {
    id: 'salthouse-dock',
    name: 'Salthouse Dock',
    themes: ['waterfront', 'hidden'],
    lat: 53.4015,
    lng: -2.9910,
    distanceToFinish: 150,
    feature: 'The oldest dock in Liverpool, now a marina, adjacent to Albert Dock.',
    clues: {
      easy: 'Find the old dock full of boats, right next to Albert Dock.',
      medium:
        'A small dock sits between Albert Dock and the shopping streets. Find the marina and the lock gates at its entrance.',
      hard: 'Reach Salthouse Dock. Identify the year it was built and find the name of the engineer who designed its original lock system, shown on the heritage board.',
    },
    reveal: 'Salthouse Dock \u2014 the oldest enclosed commercial dock in the world.',
  },
  {
    id: 'queen-square',
    name: 'Queen Square',
    themes: ['urban'],
    lat: 53.4085,
    lng: -2.9815,
    distanceToFinish: 990,
    feature: 'A pedestrian square behind Lime Street with a bronze of John Lennon as a boy.',
    clues: {
      easy: 'Find the pedestrian square behind Lime Street station with a statue of a young boy.',
      medium:
        'A square behind the station has a bronze statue of a young John Lennon. Find it and note what he is sitting on.',
      hard: 'Reach Queen Square. Identify the sculptor of the Lennon statue and find the plaque describing his childhood connection to this area.',
    },
    reveal: 'Queen Square \u2014 home to the statue of a young John Lennon.',
  },
  {
    id: 'georgian-quarter',
    name: 'Georgian Quarter (Hope Street)',
    themes: ['urban', 'hidden'],
    lat: 53.4025,
    lng: -2.9720,
    distanceToFinish: 900,
    feature: 'A elegant district of Georgian terraces between the two cathedrals.',
    clues: {
      easy: 'Walk down the elegant street of Georgian terraces that links the two cathedrals.',
      medium:
        'A street of fine Georgian terraces runs between the Anglican and Catholic cathedrals. Find the one with a blue plaque commemorating a famous resident.',
      hard: 'Walk the length of Hope Street. Identify the two cathedrals at either end and find the plaque marking the site of the original Everyman Theatre, noting the year it first opened.',
    },
    reveal: 'The Georgian Quarter \u2014 a streetscape frozen in the 18th century.',
  },
  {
    id: 'mns-bank-arena',
    name: 'M&S Bank Arena & Convention Centre',
    themes: ['waterfront', 'music'],
    lat: 53.3975,
    lng: -2.9935,
    distanceToFinish: 350,
    feature: 'A large arena and convention centre on the Kings Dock, next to Albert Dock.',
    clues: {
      easy: 'Find the big arena and convention centre next to Albert Dock, with a curved roof.',
      medium:
        'A large venue with a distinctive curved roof sits on Kings Dock, next to Albert Dock. Find the main entrance and the list of past events on the signage.',
      hard: 'Reach the M&S Bank Arena. Identify the year the venue opened (as the Echo Arena) and find the name of the architect, shown on the heritage board near the entrance.',
    },
    reveal: 'The M&S Bank Arena \u2014 Liverpool\u2019s major waterfront venue.',
  },
];

export const FINISH_LOCATION = LOCATIONS.find((l) => l.id === 'albert-dock')!;
